#SPDX-License-Identifier: MIT-0
galaxy_info:
  author: greg
  description: Configures Alaveteli settings in general.yml

  license: MIT

  min_ansible_version: "2.9"

  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy

  galaxy_tags:
    - alaveteli
    - configuration
    - foi
    - settings

dependencies: []
